# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Composer Dependencies
        run: composer update --no-ansi --no-interaction --prefer-lowest --prefer-stable --prefer-dist
        
      - name: Install NPM Dependencies
        run: npm install
        
      - name: Build Site
        run: npm run production
        
      - name: Stage Files
        run: git add -f build_production
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Build for deploy"
          
      - name: Publish
        run: |
          git subtree split --prefix build_production -b gh-pages
          git push -f origin gh-pages:gh-pages
